name: EKS Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Message
        run: echo "Deploying to EKS..."

      - name: Show Files
        run: ls -la
